apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  type: NodePort
  selector:
    app: http 
  ports:
    - protocol: TCP
      port: 8085 
      targetPort: 80 
      nodePort: 30007
