apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
  labels:
    app: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: "{{ .Values.images.repository }}/{{ .Values.images.mediawiki.name }}:{{ .Values.images.mediawiki.tag }}"
        imagePullPolicy: "{{ .Values.images.pullPolicy }}" 
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: test-cred    
