apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "{{ .Values.images.repository }}/{{ .Values.images.mediawikijob.name }}:{{ .Values.images.mediawikijob.tag }}"
        imagePullPolicy: "{{ .Values.images.pullPolicy }}"
        command: ["/bin/sh","-c"]
        args: ["mysql -u root -p < /tmp/prepare_db.sql"] 
      imagePullSecrets:
        - name: test-cred
