apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort 
  selector:
    app: http 
  ports:
    - protocol: TCP
      port: 8090 
      targetPort: 3306 
      nodePort: 30007
