# Default values for stackHelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imagePullSecrets:
    - name: test-cred
images:
  repository: docker.io/kunzsoni 
  pullPolicy: Always 
  mediawiki:
    name: mediawiki
  # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  mediawikidb:
    name: mediawikidb
    tag: latest
  mediawikijob:  
    name: util 
    tag: latest
